WITH FREE_SPACE
        AS (  SELECT TABLESPACE_NAME,
                     ROUND (SUM (BYTES) / 1024 / 1024, 2) AS FREE_SPACE
                FROM DBA_FREE_SPACE
            GROUP BY TABLESPACE_NAME),
     TOTAL_SPACE
        AS (  SELECT TABLESPACE_NAME, SUM (BYTES) / 1024 / 1024 AS TBS_SIZE
                FROM DBA_DATA_FILES
            GROUP BY TABLESPACE_NAME
            UNION
              SELECT TABLESPACE_NAME, SUM (BYTES) / 1024 / 1024 TBS_SIZE
                FROM DBA_TEMP_FILES
            GROUP BY TABLESPACE_NAME)
SELECT TOTAL_SPACE.TABLESPACE_NAME,
       TBS_SIZE SIZE_MB,
       FREE_SPACE.FREE_SPACE FREE_MB
  FROM FREE_SPACE, TOTAL_SPACE
 WHERE FREE_SPACE.TABLESPACE_NAME(+) = TOTAL_SPACE.TABLESPACE_NAME;
