kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scale-rolebinding
  namespace: app-etiop-dev-cu-infrastructure
  uid: 3bc337d1-96c2-4dcc-a945-27a08eed703f
  resourceVersion: '111817182'
  creationTimestamp: '2024-06-07T14:02:13Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2024-06-07T14:02:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:roleRef': {}
        'f:subjects': {}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: app-etiop-dev-cu-infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scale-role
