FROM dokken/centos-8

RUN yum upgrade -y && yum install -y openssh-server ncurses python3
RUN ssh-keygen -A
RUN echo 'root:root1' | chpasswd
RUN sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]