global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/ba23311a-456e-450b-b586-04b88e3417fc'
          send_resolved: false