services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command: 
    - --config.file=/etc/prometheus/prometheus.yml 
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=30d
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --web.enable-lifecycle
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
      - prometheus-tsdb:/prometheus
    ports:
      - 9090:9090

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - '9115:9115'

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/data
    ports:
      - "9093:9093"


volumes:
  alertmanager-data:
  prometheus-tsdb: